"""initial migration

Revision ID: 0854a5977407
Revises: 81e261c2f5e1
Create Date: 2024-10-07 19:17:19.415835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0854a5977407'
down_revision: Union[str, None] = '81e261c2f5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('register_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_register_user_id'), ['id'], unique=False)

    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['register_user.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['register_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_id'))

    op.drop_table('donations')
    with op.batch_alter_table('register_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_register_user_id'))

    op.drop_table('register_user')
    # ### end Alembic commands ###
